name: PRODUCTION ENV
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      # validate template
      - run: sam validate --template template.yaml

      # free disk space
      - run: sudo swapoff -a
      - run: sudo rm -f /swapfile
      - run: sudo apt clean
      - run: docker rmi $(docker image ls -aq)
      - run: df -h
      
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name prod-hello-world --s3-bucket hello-deploy --s3-prefix prod --capabilities CAPABILITY_IAM --region eu-west-1